version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: api_password
      POSTGRES_DB: files
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - files_db:/var/lib/postgresql/data
    restart: no

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: api_user
      MINIO_ROOT_PASSWORD: api_password
    command: server --console-address ":9001" /data

volumes:
  files_db:
    driver: local
  minio_storage: {}